blank_issues_enabled: false
contact_links:
  - name: Zuniswap Community discord
    url: 
    about: Ask questions and discuss the roadmap here.
  - name: Zuniswap - Feedback
    url: 
    about: Share your feedback with the GitHub team.
